language: python

sudo: required

services:
  - docker

env:
  - KAFKA_ADVERTISED_HOST_NAME=localhost,PUBSUB_PROJECT="eco-spirit-208613",GOOGLE_APPLICATION_CREDENTIALS=/tmp/eco-spirit-208613-5c70334d972b.json,SPARK_HOME=/tmp/spark

python:
  - "3.6"

before_install:
  - docker pull mongo
  - docker pull google/cloud-sdk
  - docker pull wurstmeister/kafka
  - ./bin/ci/travis/before-install.sh

install:
  - pip install -r requirements.txt

script:
  - docker-compose up &
  - sleep 5
  - tox -e flake8,travis
  - codecov --token=$CODECOV_TOKEN