language: python

sudo: required

services:
  - docker

env:
  - KAFKA_ADVERTISED_HOST_NAME=localhost PUBSUB_PROJECT="eco-spirit-208613" SPARK_HOME=/tmp/spark GOOGLE_APPLICATION_CREDENTIALS=/tmp/eco-spirit-208613-5c70334d972b.json

python:
  - "3.6"

before_install:
  - ./bin/run-docker-environment.sh
  - ./bin/wait-for-docker-environment.sh
  - ./bin/ci/travis/before-install.sh

install:
  - pip install -r requirements.txt

script:
  - tox -e flake8,travis

after_success:
  - ./bin/ci/travis/after-success.sh