language: python

sudo: required

services:
  - docker

env:
  - KAFKA_ADVERTISED_HOST_NAME=localhost

python:
  - "3.5"
  - "3.6"

before_install:
  - docker-compose up

install:
  - pip install -r requirements.txt

script:
  - tox -e flake8,travis