language: python

sudo: required

services:
  - docker

env:
  - KAFKA_ADVERTISED_HOST_NAME=localhost

python:
  - "3.5"
  - "3.6"

before_install:
  - docker pull mongo
  - docker pull google/cloud-sdk
  - docker pull wurstmeister/kafka

install:
  - pip install -r requirements.txt

script:
  - docker-compose up &
  - sleep 5
  - tox -e flake8,travis