version: '3.5'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - poc_anomaly_detection
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "feed:1:1,predict:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - poc_anomaly_detection
    depends_on:
      - zookeeper

networks:
  poc_anomaly_detection:
    name: poc_anomaly_detection

