version: '3'

services:

  mongo:
    image: mongo
    volumes:
      - anomdec-mongo:/data/db
    ports:
      - "27017:27017"

  pubsub:
    image: google/cloud-sdk
    command: gcloud alpha emulators pubsub start --project testing --verbosity=debug --user-output-enabled --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "test1:1:1,test2:1:1"
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  anomdec-mongo:
