version: '3'

services:
  poc_zookeeper:
    image: wurstmeister/zookeeper
    container_name: poc_zookeeper
    ports:
      - "2181:2181"
    networks:
      - poc_anomaly_detection
  poc_kafka:
    image: wurstmeister/kafka:0.11.0.1
    container_name: poc_kafka
    ports:
      - "9092:9092"
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ZOOKEEPER_CONNECT: poc_zookeeper:2181
      KAFKA_CREATE_TOPICS: "feed:1:1,predict:1:1"
      KAFKA_ADVERTISED_HOST_NAME: poc_kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - poc_anomaly_detection
    depends_on:
      - poc_zookeeper

  kafka_wait_for:
    image: wurstmeister/kafka
    container_name: kafka_wait_for
    working_dir: /var/tmp
    volumes:
      - ./bin/:/var/tmp
    command: /bin/bash wait-for-kafka.sh
    environment:
      ZOOKEEPER_HOST: poc_zookeeper:2181
      KAFKA_PATH: /opt/kafka
    networks:
      - poc_anomaly_detection
    depends_on:
      - poc_kafka

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poc_anomaly_detection
    links:
      - poc_kafka
    networks:
      - poc_anomaly_detection
    environment:
      BOOTSTRAP_SERVER: 192.168.99.100:9092
      BROKER_SERVER: 192.168.99.100:9092
      INPUT_TOPIC: "feed"
      OUTPUT_TOPIC: "predict"
    depends_on:
      - kafka_wait_for


networks:
  poc_anomaly_detection:
    driver: bridge

