version: 1

websocket: ws://localhost:5000/ws/

streams:
  - name: my_kafka_source_one
    source:
      type: kafka
      params:
        brokers: localhost:9092
        in: test1
    engine:
      type: robust
      params:
        window: 30
        threshold: 0.9999
    sink:
      - name: sqlite
        type: repository
        repository:
          type: sqlite
          params:
            database: /tmp/my_kafka_source_one.sqlite
    warmup:
      - name: sqlite
        repository:
          type: sqlite
          params:
            database: /tmp/my_kafka_source_one.sqlite